Feature/continuous record badge
prography/5th-pizza-back pull request #2
Opened 2020-01-26 12:14 UTC by moonelysian

리팩토링 부탁합니다아

2020-01-26 12:25 UTC, geusan requested changes

2020-01-26 12:25 UTC, geusan commented on src/routes/index.js
> +router.use('/badges', badge);
테스트 코드에도 badge 에 요청을 넣는 코드가 있는데 같이 바꿔주는게 어떨까?

2020-01-28 01:24 UTC, moonelysian commented on src/routes/index.js
> +router.use('/badges', badge);
으디 있어여?

2020-01-28 01:45 UTC, geusan commented on src/routes/index.js
> +router.use('/badges', badge);
src/tests/features/BadgeController.spec.js 가 있을거야!

2020-01-28 10:39 UTC, moonelysian commented on src/routes/index.js
> +router.use('/badges', badge);
고쳤으

2020-01-28 10:49 UTC, moonelysian commented on src/routes/index.js
> +router.use('/badges', badge);
머지 하겠습니당

2020-01-28 10:49 UTC, merged